export const productCategories = [
   "Business and Entrepreneurship",
   "Personal Finance and Investment",
   "Marketing and Sales",
   "Technology and Software Development",
   "Graphic Design and Multimedia",
   "Web Development and Programming",
   "Data Science and Analytics",
   "Artificial Intelligence and Machine Learning",
   "Content Creation and Blogging",
   "Social Media Management",
   "Photography and Videography",
   "E-commerce and Online Stores",
   "SEO and Digital Marketing",
   "Health and Wellness",
   "Fitness and Exercise",
   "Mental Health and Psychology",
   "Nutrition and Dieting",
   "Yoga and Meditation",
   "Self-Improvement and Motivation",
   "Leadership and Management",
   "Human Resources and Recruitment",
   "Project Management",
   "Public Speaking and Communication",
   "Education and Learning",
   "Academic Research and Writing",
   "Languages and Linguistics",
   "Science and Technology",
   "History and Culture",
   "Art and Creativity",
   "Music and Performing Arts",
   "Film and Video Production",
   "Cooking and Culinary Arts",
   "Travel and Adventure",
   "Parenting and Family",
   "Personal Development and Growth",
   "Home Improvement and DIY",
   "Gardening and Landscaping",
   "Pet Care and Animal Training",
   "Fashion and Style",
   "Beauty and Grooming",
   "Interior Design and Decoration",
   "Legal Advice and Services",
   "Real Estate and Property",
   "Sports and Recreation",
   "Gaming and eSports",
   "Photography and Digital Imaging",
   "Health and Safety",
   "Environmental Awareness and Sustainability",
   "Non-Profit and Charity Work",
   "Freelancing and Remote Work",
   "Artificial Intelligence and Robotics",
   "Philosophy and Ethics",
];
